Group7Phase2/JohnCandy.WebApi/Controllers/ShopController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace JohnCandy.WebApi.Controllers
{
    public class ShopController : Controller
    {
        // GET: Shop
        public ActionResult Index()
        {
            return Redirect(Url.Content("~/App/Views/index.html"));
        }
    }
}

Group7Phase2/JohnCandy.WebApi/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.Helpers;
using System.Web.Security;
using JohnCandy.WebApi.Models;
using JohnCandy.WebApi;

namespace WebAdmin.Controllers
{
    public class UsersController : Controller
    {
        private WebContext db = new WebContext();

        //login - get
        [HttpGet]
        public ActionResult Login()
        {
            return View();
        }

        //login - post
        [HttpPost]
        public ActionResult Login(string email, string password, string returnUrl)
        {
            //if(email == null)
            //{
            //    ModelState.AddModelError("Email", "Must have a valid email to log in.");
            //    return View(new User());
            //}

            if (password == null)
            {
                ModelState.AddModelError("Password", "Must have a valid password to log in.");
                return View(new User());
            }
     
            var loginUser = db.Users.FirstOrDefault(u => u.Email == email);
            if (loginUser == null)
            {
                ModelState.AddModelError("Email", "Must have a valid email to log in.");
                return View(new User());
            }
            if (!Crypto.VerifyHashedPassword(loginUser.Password, password))
            {
                loginUser.Password = "";
                return View(loginUser);
            }
            
            FormsAuthentication.SetAuthCookie(email, true);

            if (Request.QueryString["ReturnURL"] != null)
            {
                return Redirect(Request.QueryString["ReturnURL"]);
            }
            return RedirectToAction("Index");
        }

        public ActionResult Logout()
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("Login");
        }

        [Authorize]
        // GET: Users
        public async Task<ActionResult> Index()
        {
            return View(await db.Users.ToListAsync());
        }

        [Authorize]
        // GET: Users/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = await db.Users.FindAsync(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        [Authorize]
        // GET: Users/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Users/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "ID,Email,Password,FName,LName")] User user)
        {
            if (ModelState.IsValid)
            {
                user.Password = Crypto.HashPassword(user.Password);
                db.Users.Add(user);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            
            return View(user);
        }

        [Authorize]
        // GET: Users/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = await db.Users.FindAsync(id);
            if (user == null)
            {
                return HttpNotFound();
            }

            user.Password = "";
            return View(user);
        }

        // POST: Users/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "ID,Email,Password, FName, LName")] User user)
        {
            if (ModelState.IsValid)
            {
                if (user.Password == null)
                {
                    ModelState.AddModelError("Password", "Enter your password to update.");
                }
                user.Password = Crypto.HashPassword(user.Password);
                db.Entry(user).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

           

            return View(user);
        }

        [Authorize]
        // GET: Users/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = await db.Users.FindAsync(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // POST: Users/Delete/5
        [Authorize]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            User user = await db.Users.FindAsync(id);
            db.Users.Remove(user);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Group7Phase2/JohnCandy.WebApi/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title - John Candy Shop</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/foundation/css")
    @*@Scripts.Render("~/bundles/modernizr")*@
</head>
<body>
    <div class="sticky">
        <nav class="top-bar fixed" data-topbar="" role="navigation">
            <section class="top-bar-section">
                <ul class="title-area">
                    <li class="name">
                        <h1>
                            <a href="@Url.Action("Index", "Shop")">John Candy</a>
                        </h1>
                    </li>
                </ul>
                <ul class="left">
                    <li class="top">@Html.ActionLink("Store", "Index", "Shop", new { area = "" }, null)</li>
                </ul>
                <ul class="right">
                    @if (System.Web.HttpContext.Current.User != null && System.Web.HttpContext.Current.User.Identity.IsAuthenticated)
                    {
                        <li class="top">@Html.ActionLink("Logout", "Logout", "Users", new { area = "" }, null)</li>
                    }
                </ul>
            </section>
        </nav>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/foundation")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
<script>
    $(document).foundation();
</script>
</body>
</html>